# Application under test configuration
application:
  baseUrl: https://www.lambdatest.com/selenium-playground/simple-form-demo
  driversPath: ~/.m2/repository/webDriver   # Path to drivers executables

# Extent Report configuration
extent:
  documentTitle: Selenium Report  # Title of the html page
  reportName: Selenium Report   # Name shown in the header of the report
  theme: STANDARD   # Theme used in the report
  timeStampFormat: EEEE dd/MM/yyyy, hh:mm a (zzz)   # Timestamp of each test start time and end time

# WebDriver configuration
webDriver:
  waitTimeout: 1    # Number of seconds selenium will wait before throwing a TimeoutException when an element isn't found. Injected in webDriverWaits
  pageLoadingWaitTimeout: 10   # Number of seconds that selenium will wait before throwing a TimeoutException because page wasn't loaded. Injected in webDriverWaits
  downloadWaitTimeout: 15   # Number of seconds that selenium will wait before throwing a TimeoutException on file download. Injected in webDriverWaits
  scriptWaitTimeout: 10   # Number of seconds that selenium will wait before throwing a ScriptTimeoutException. Injected in webDriverWaits
  defaultEventListenerEnabled: true

  grid:
    url: http://127.0.0.1:4444/wd/hub/
    capabilities: { }

  # Chrome capabilities. See: https://chromedriver.chromium.org/capabilities
  chrome:
    capabilities: { }
    arguments: [ ]
    experimentalOptions:
      prefs:
        download.prompt_for_download: false
        download.directory_upgrade: true
        safebrowsing.enabled: true

  # Firefox capabilities. See: https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions
  firefox:
    binary: null
    args: [ ]
    logLevel: INFO
    preferences:
      browser.download.folderList: 2
      browser.download.useDownloadDir: true
      browser.helperApps.neverAsk.saveToDisk: application/pdf
      pdfjs.disabled: true

  # Internet Explorer capabilities. See: https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#ie-specific
  ie:
    capabilities: { }

  # Edge capabilities. See: https://learn.microsoft.com/en-us/microsoft-edge/webDriver-chromium/capabilities-edge-options
  edge:
    capabilities: { }

# Selenium internal logging levels
seleniumLogs:
  browser: INFO
  client: INFO
  driver: INFO
  performance: OFF
  profiler: OFF
  server: OFF

# Events fired by the webDriver and automatically logged and added to the report. Specify a level among OFF, TRACE, DEBUG, INFO, WARN.
events:
  beforeAnyCall: OFF
  afterAnyCall: OFF
  onError: DEBUG
  beforeAnyWebDriverCall: OFF
  afterAnyWebDriverCall: OFF
  beforeGet: INFO
  afterGet: OFF
  beforeGetCurrentUrl: OFF
  afterGetCurrentUrl: OFF
  beforeGetTitle: OFF
  afterGetTitle: OFF
  beforeFindElement: DEBUG
  afterFindElement: OFF
  beforeFindElements: DEBUG
  afterFindElements: OFF
  beforeGetPageSource: OFF
  afterGetPageSource: DEBUG
  beforeClose: DEBUG
  afterClose: OFF
  beforeQuit: DEBUG
  afterQuit: OFF
  beforeGetWindowHandles: DEBUG
  afterGetWindowHandles: OFF
  beforeGetWindowHandle: DEBUG
  afterGetWindowHandle: OFF
  beforeExecuteScript: DEBUG
  afterExecuteScript: OFF
  beforeExecuteAsyncScript: DEBUG
  afterExecuteAsyncScript: OFF
  beforePerform: OFF
  afterPerform: OFF
  beforeResetInputState: OFF
  afterResetInputState: OFF
  beforeAnyWebElementCall: OFF
  afterAnyWebElementCall: OFF
  beforeClick: INFO
  afterClick: OFF
  beforeSubmit: INFO
  afterSubmit: OFF
  beforeSendKeys: INFO
  afterSendKeys: OFF
  beforeClear: DEBUG
  afterClear: OFF
  beforeGetTagName: OFF
  afterGetTagName: INFO
  beforeGetAttribute: OFF
  afterGetAttribute: INFO
  beforeIsSelected: OFF
  afterIsSelected: INFO
  beforeIsEnabled: OFF
  afterIsEnabled: INFO
  beforeGetText: OFF
  afterGetText: INFO
  beforeIsDisplayed: OFF
  afterIsDisplayed: INFO
  beforeGetLocation: OFF
  afterGetLocation: INFO
  beforeGetSize: OFF
  afterGetSize: INFO
  beforeGetCssValue: OFF
  afterGetCssValue: INFO
  beforeAnyNavigationCall: INFO
  afterAnyNavigationCall: OFF
  beforeTo: INFO
  afterTo: OFF
  beforeBack: INFO
  afterBack: OFF
  beforeForward: INFO
  afterForward: OFF
  beforeRefresh: INFO
  afterRefresh: OFF
  beforeAnyAlertCall: OFF
  afterAnyAlertCall: OFF
  beforeAccept: INFO
  afterAccept: OFF
  beforeDismiss: INFO
  afterDismiss: OFF
  beforeAnyOptionsCall: OFF
  afterAnyOptionsCall: OFF
  beforeAddCookie: TRACE
  afterAddCookie: OFF
  beforeDeleteCookieNamed: TRACE
  afterDeleteCookieNamed: OFF
  beforeDeleteCookie: TRACE
  afterDeleteCookie: OFF
  beforeDeleteAllCookies: TRACE
  afterDeleteAllCookies: OFF
  beforeGetCookies: TRACE
  afterGetCookies: OFF
  beforeGetCookieNamed: TRACE
  afterGetCookieNamed: OFF
  beforeAnyTimeoutsCall: OFF
  afterAnyTimeoutsCall: OFF
  beforeImplicitlyWait: OFF
  afterImplicitlyWait: OFF
  beforeSetScriptTimeout: OFF
  afterSetScriptTimeout: OFF
  beforePageLoadTimeout: OFF
  afterPageLoadTimeout: OFF
  beforeAnyWindowCall: OFF
  afterAnyWindowCall: OFF
  beforeSetSize: OFF
  afterSetSize: INFO
  beforeGetPosition: OFF
  afterGetPosition: INFO
  beforeSetPosition: OFF
  afterSetPosition: INFO
  beforeMaximize: DEBUG
  afterMaximize: OFF
  beforeFullscreen: DEBUG
  afterFullscreen: OFF
